// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<APSConnection>>
abstract class ApsConnection implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<APSState>>
abstract class ApsState implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ArcAnisetteClient < DefaultAnisetteProvider >>>
abstract class ArcAnisetteClientDefaultAnisetteProvider
    implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < CloudKitClient < DefaultAnisetteProvider > >>>
abstract class ArcCloudKitClientDefaultAnisetteProvider
    implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < CloudMessagesClient < DefaultAnisetteProvider > >>>
abstract class ArcCloudMessagesClientDefaultAnisetteProvider
    implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < FTClient >>>
abstract class ArcFtClient implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < FindMyClient < DefaultAnisetteProvider > >>>
abstract class ArcFindMyClientDefaultAnisetteProvider
    implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < IMClient >>>
abstract class ArcImClient implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < IdmsAuthListener >>>
abstract class ArcIdmsAuthListener implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < KeychainClient < DefaultAnisetteProvider > >>>
abstract class ArcKeychainClientDefaultAnisetteProvider
    implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < Mutex < AppleAccount < DefaultAnisetteProvider > > >>>
abstract class ArcMutexAppleAccountDefaultAnisetteProvider
    implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < Mutex < Option < CircleClientSession < DefaultAnisetteProvider > > > >>>
abstract class ArcMutexOptionCircleClientSessionDefaultAnisetteProvider
    implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < Mutex < Vec < ActiveCircleSession > > >>>
abstract class ArcMutexVecActiveCircleSession implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < PasswordManager < DefaultAnisetteProvider > >>>
abstract class ArcPasswordManagerDefaultAnisetteProvider
    implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < ProfilesClient < DefaultAnisetteProvider > >>>
abstract class ArcProfilesClientDefaultAnisetteProvider
    implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < Sender < PushMessage > >>>
abstract class ArcSenderPushMessage implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < SharedPushState >>>
abstract class ArcSharedPushState implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < StatusKitClient < DefaultAnisetteProvider > >>>
abstract class ArcStatusKitClientDefaultAnisetteProvider
    implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Arc < TokenProvider < DefaultAnisetteProvider > >>>
abstract class ArcTokenProviderDefaultAnisetteProvider
    implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NSArray < LPIconMetadata >>>
abstract class NsArrayLpIconMetadata implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NSArray < LPImageMetadata >>>
abstract class NsArrayLpImageMetadata implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Sender < () >>>
abstract class Sender implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SyncManager < DefaultAnisetteProvider , MyFilePackager >>>
abstract class SyncManagerDefaultAnisetteProviderMyFilePackager
    implements RustOpaqueInterface {}
